# Generated by Django 5.2 on 2025-06-18 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem", models.CharField(max_length=200)),
                ("destino", models.CharField(max_length=200)),
                ("horario_saida", models.DateTimeField()),
                ("assentos_disponiveis", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoCarona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_solicitacao", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Carona aceita", "Aceita"),
                            ("Carona recusada", "Recusada"),
                            ("Solicitação pendente", "Pendente"),
                        ]
                    ),
                ),
                (
                    "carona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caronas.carona"
                    ),
                ),
                (
                    "passageiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
