# Generated by Django 5.2 on 2025-06-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caronas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaocarona",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACEITA", "Carona aceita"),
                    ("RECUSADA", "Carona recusada"),
                    ("PENDENTE", "Solicitação pendente"),
                ],
                max_length=50,
            ),
        ),
    ]
